# Generated by Django 2.1.5 on 2020-10-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
