# Generated by Django 2.1.5 on 2020-10-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20201029_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
