# Generated by Django 2.1.5 on 2020-10-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=255)),
                ('exact_phrase', models.CharField(blank=True, max_length=255)),
                ('minus_words', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('bg', 'Bulgarian'), ('bn', 'Bengali'), ('en', 'English'), ('de', 'German'), ('fr', 'French'), ('it', 'Italian'), ('pt-BR', 'Portuguese(Brazil)'), ('pt-PT', 'Portuguese(Portugal)'), ('cs', 'Czech'), ('hr', 'Croatian'), ('da', 'Danish'), ('nl', 'Dutch'), ('et', 'Estonian'), ('fi', 'Finnish'), ('el', 'Greek'), ('no', 'Norwegian'), ('nn', 'Norwegian (Nynorsk)'), ('hi', 'Hindi'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('ja', 'Japanese'), ('lv', 'Latvian'), ('lt', 'Lithuanian'), ('fa', 'Persian'), ('pl', 'Polish'), ('ro', 'Romanian'), ('ru', 'Russian'), ('es', 'Spanish'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sw', 'Swahili'), ('sv', 'Swedish'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('ko', 'Korean'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese')], max_length=255)),
            ],
        ),
    ]
