# Generated by Django 2.1.5 on 2020-10-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmodel',
            name='minus_words',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
